#!/bin/sh
# This script was created by make-mzscheme-launcher

# {{{ bindir
bindir="/home/lackita/racket/bin"
# }}} bindir

exec "${bindir}/racket" -N "$0" '-I' 'scheme/init' '-qt-' '/home/lackita/checkit/racketform/racketform.rkt'  ${1+"$@"}
